### ISSUE TITLE
Logo für EAuthoring erzeugen

### ISSUE THREAD

**Issue by belaso** [belaso/EAuthoring#10]
- [x] Splashscreen,
- [x] Icon beim Start der Software
sollen eingebaut werden.

**Comment by belaso** [comment]
Erster Entwurf:
![logo eauthoring](https://cloud.githubusercontent.com/assets/1709299/8274032/6af5ef16-1886-11e5-818c-56e4b585766c.png)

**Comment by tabea444** [comment]
*  erster Eindruck: schon viel besser
* grauer rechter Rand zu lang, vielleicht ganz weglassen
* finde Stift auch nicht ganz OK
* Vorschläge für Stift: 
  * etwas größer, steiler
  * Farbtausch von orange und blau
  * statt unterstreichen,  Stift in letzten Buchstaben integrieren, als ob nicht ganz zu Ende geschrieben
* Hintergrund weiß finde ich gut, vermisse keine Papierkörnung
* noch einmal Beispiele mit verschiedenen Schriftarten nebeneinander stellen

**Comment by tabea444** [comment]
* Sorry! Hab den falschen Button geklickt ;-)

**Comment by tabea444** [comment]
# Dritter Versuch !!!

**Comment by belaso** [comment]
OK, gute Hinweise! Ich werde mehrere Versionen mit leichten Veränderungen zusammenstellen, damit wir besser vergleichen können.

**Comment by belaso** [comment]
Zusammenarbeit mit @tabea444 an dem Splashscreen liefert folgenden Stand:

![logo eauthoring-01](https://cloud.githubusercontent.com/assets/1709299/8293370/433df374-1935-11e5-965e-81c689954722.png)

**Comment by belaso** [comment]
@tabea444 Sollen wir bei diesem Logo bleiben? Ich würde momentan dazu tendieren und nicht mehr viel Arbeit da reinstecken. Würde dann in Richtung Issue #9 gehen und mit dem Screencast anfangen.

**Comment by tabea444** [comment]
Ok, können den Splashscreen;-) heute Abend noch einmal kurz besprechen und dann schließen. Kannst schon mal in Richtung #9 gehen.

**Comment by belaso** [comment]
Nächste Weiterentwicklung:
![splash](https://cloud.githubusercontent.com/assets/1709299/8766233/b6068c0e-2e2f-11e5-8291-b6f67574d29f.png)

**Comment by belaso** [comment]
Letzter TODO: Erzeugung einer ICO Datei, d.h. Windows Icon muss noch generiert werden.
